### ISSUE TITLE
what is corpus_title_set in preprocess/process_wiki_page.py ?

### ISSUE THREAD

**Issue by gw16** [TIGER-AI-Lab/LongRAG#1]
I couldn't figure out what corpus_title_set means in process_wiki_page.py

**Comment by XMHZZ2018** [comment]
Thanks for your question. I just updated the code and README for better illustration of this option. The key is used to filter the NQ dataset. In the original DPR paper, certain Wikipedia pages, such as list pages and disambiguation pages, were removed, reducing the total number of Wikipedia pages from 5 million to 3 million. For a fair comparison, we also chose to exclude these pages in our retrieval corpus. (For HotpotQA, we did not remove any pages, so the number of Wikipedia pages remains at 5 million.) You can download the DPR's processed version from the link of DPR repo(https://dl.fbaipublicfiles.com/dpr/wikipedia_split/psgs_w100.tsv.gz).

Additionally, just FYI, I tested whether the hyperlinks from the 2 million removed Wikipedia pages are useful. While it is not fair to use them in the retrieval corpus, they could be employed to group related documents. However, I found that this approach only provided a very marginal improvement. Consequently, in the final version, we also did not use the hyperlinks from these 2 million pages for NQ.

**Comment by gw16** [comment]
> Thanks for your question. I just updated the code and README for better illustration of this option. The key is used to filter the NQ dataset. In the original DPR paper, certain Wikipedia pages, such as list pages and disambiguation pages, were removed, reducing the total number of Wikipedia pages from 5 million to 3 million. For a fair comparison, we also chose to exclude these pages in our retrieval corpus. (For HotpotQA, we did not remove any pages, so the number of Wikipedia pages remains at 5 million.) You can download the DPR's processed version from the link of DPR repo(https://dl.fbaipublicfiles.com/dpr/wikipedia_split/psgs_w100.tsv.gz).
> 
> Additionally, just FYI, I tested whether the hyperlinks from the 2 million removed Wikipedia pages are useful. While it is not fair to use them in the retrieval corpus, they could be employed to group related documents. However, I found that this approach only provided a very marginal improvement. Consequently, in the final version, we also did not use the hyperlinks from these 2 million pages for NQ.

Thanks for your response. 
And one more thing, what is WIKI_DUMP_FILE_IN in extract_and_clean_wiki_dump.sh? 
I ran python3 -m wikiextractor.WikiExtractor enwiki-latest-pages-articles1.xml-p1p41242.bz2 --json -l -c -q, but the bz2 files(AA, AB, AC, AD, AE in my case) in the 'text' directory obtained this way show a corrupted file error when running process_wiki_page.sh.

**Comment by XMHZZ2018** [comment]
Hi, I haven't encountered the "corrupted file error" on my end, but I'd be happy to help you debug. First, could you please check if the corrupted file error occurs for every subdirectory or just one specific subdirectory or file? Second, could you try loading a single bz2 file using a similar method as in the process_wiki function to see if it works?
Third, this is the raw data I was using: https://archive.org/download/enwiki-20181220/, which is the WIKI_DUMP_FILE_IN, is it the same as yours?

**Comment by gw16** [comment]
> Hi, I haven't encountered the "corrupted file error" on my end, but I'd be happy to help you debug. First, could you please check if the corrupted file error occurs for every subdirectory or just one specific subdirectory or file? Second, could you try loading a single bz2 file using a similar method as in the process_wiki function to see if it works? Third, this is the raw data I was using: https://archive.org/download/enwiki-20181220/, which is the WIKI_DUMP_FILE_IN, is it the same as yours?

Could you tell me the exact name? (ex .enwiki-20181220-pages-articles1.xml-p10p30302.bz2)

**Comment by XMHZZ2018** [comment]
This one: (https://archive.org/download/enwiki-20181220/enwiki-20181220-pages-articles.xml.bz2)
