### ISSUE TITLE
Question for retrieve_tevatron.sh.

### ISSUE THREAD

**Issue by gw16** [TIGER-AI-Lab/LongRAG#2]
When running sh scripts/run_retrieve_tevatron.sh, which path should I use?
Should I set the dataset_path in sh scripts/run_retrieve_tevatron.sh to the directory where the custom data doc_group_map.pickle, group_size.pickle, group_text.pickle, and group_title.pickle are stored after running sh scripts/group_documents.sh?

**Comment by XMHZZ2018** [comment]
Hi @gw16 , I'm sorry that I forget to reply this one. The group_text.pickle file contains the long retrieval units used for retrieval. You can use a long embedding model that supports 4K or even longer context for retrieval on this directly, or you can use the approximation method (Max-P) that we used in our paper. (Currently, our results have shown that existing long embedding models do not perform better than the approximation method.)

One thing to note is that you need to use the correct format as required by Tevatron (e.g., column names). Alternatively, you can update the config file in Tevatron. Here’s a sample format from the official Tevatron repository: https://huggingface.co/datasets/Tevatron/wikipedia-nq-corpus. ("docid", "text" are the most important fields; "title" field is used in their code, but you could option not to use.)
